version: 1.0.{build}
pull_requests:
  do_not_increment_build_number: true
skip_branch_with_pr: true
image: Visual Studio 2017
configuration: Debug
platform: Any CPU
build_script:
- cmd: >-
    IF /I "%APPVEYOR_REPO_TAG%" EQU "TRUE" SET Configuration=Release

    MSBuild /BinaryLogger /Logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
artifacts:
- path: '**\*.nupkg'
  name: NuGet Packages
on_failure:
- ps: Get-ChildItem .\*log -Recurse | % { Push-AppveyorArtifact $_.FullName -FileName $_.Name }
