resources:
- repo: self

variables:
  ArtifactsDirectoryName: 'artifacts'
  BuildConfiguration: 'Debug'
  BuildPlatform: 'Any CPU'
  DotNetCore3Version: '3.x'
  DotNet5Version: '5.x'
  DotNet6Version: '6.x'
  DotNet7Version: '7.x'
  DotNet8Version: '8.x'
  MSBuildArgs: '"/Property:Platform=$(BuildPlatform);Configuration=$(BuildConfiguration)"'
  SignType: 'Test'

trigger:
  batch: 'true'
  branches:
    include:
    - 'main'
    - 'rel/*'
  paths:
    exclude:
    - '*.md'
pr:
  branches:
    include:
    - 'main'
    - 'rel/*'
  paths:
    exclude:
    - '*.md'

jobs:
- job: BuildAndTest
  strategy:
    matrix:
      Windows:
        vmImage: windows-latest
        osName: Windows
      Linux:
        vmImage: ubuntu-latest
        osName: Linux
      MacOS:
        vmImage: macOS-latest
        osName: MacOS
  displayName: 'Build and Test'
  pool:
    vmImage: $(vmImage)
  steps:
  - task: UseDotNet@2
    displayName: 'Install .NET Core $(DotNetCore3Version)'
    inputs:
      version: '$(DotNetCore3Version)'

  - task: UseDotNet@2
    displayName: 'Install .NET $(DotNet5Version)'
    inputs:
      version: '$(DotNet5Version)'

  - task: UseDotNet@2
    displayName: 'Install .NET $(DotNet6Version)'
    inputs:
      version: '$(DotNet6Version)'

  - task: UseDotNet@2
    displayName: 'Install .NET $(DotNet7Version)'
    inputs:
      version: '$(DotNet7Version)'
      includePreviewVersions: true

  - script: |
      powershell -NoProfile -ExecutionPolicy unrestricted -Command "[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12; &([scriptblock]::Create((Invoke-WebRequest -UseBasicParsing 'https://dot.net/v1/dotnet-install.ps1'))) -Channel 8.0 -Quality daily -InstallDir C:\hostedtoolcache\windows\dotnet"
      dotnet --info
    displayName: 'Install .NET $(DotNet8Version) (Windows)'
    condition: eq(variables.osName, 'Windows')

  - script: |
      curl -sSL https://dot.net/v1/dotnet-install.sh | bash /dev/stdin --channel 8.0 --quality daily --install-dir /opt/hostedtoolcache/dotnet
      dotnet --info
    displayName: 'Install .NET $(DotNet8Version) (Linux)'
    condition: eq(variables.osName, 'Linux')

  - script: |
      curl -sSL https://dot.net/v1/dotnet-install.sh | bash /dev/stdin --channel 8.0 --quality daily --install-dir /Users/runner/hostedtoolcache/dotnet
      dotnet --info
    displayName: 'Install .NET $(DotNet8Version) (MacOS)'
    condition: eq(variables.osName, 'MacOS')

  - task: VSBuild@1
    displayName: 'Build (Visual Studio)'
    inputs:
      msbuildArgs: '$(MSBuildArgs) "/BinaryLogger:$(ArtifactsDirectoryName)/build.binlog"'
    condition: eq(variables.osName, 'Windows')

  - task: DotNetCoreCLI@2
    displayName: 'Build (dotnet)'
    inputs:
      command: 'build'
      arguments: '$(MSBuildArgs) "/BinaryLogger:$(ArtifactsDirectoryName)/build.binlog"'
    condition: ne(variables.osName, 'Windows')

  - task: DotNetCoreCLI@2
    displayName: 'Run Unit Tests (.NET Framework v4.7.2)'
    inputs:
      command: 'test'
      arguments: '--no-restore --no-build --framework net472 /noautorsp $(MSBuildArgs) "/BinaryLogger:$(ArtifactsDirectoryName)/test-net472.binlog"'
      testRunTitle: '$(osName) .NET Framework v4.7.2'
    condition: and(succeededOrFailed(), eq(variables.osName, 'Windows'))

  - task: DotNetCoreCLI@2
    displayName: 'Run Unit Tests (.NET Core 3.1)'
    inputs:
      command: 'test'
      arguments: '--no-restore --no-build --framework netcoreapp3.1 /noautorsp $(MSBuildArgs) "/BinaryLogger:$(ArtifactsDirectoryName)/test-netcoreapp3.1.binlog"'
      testRunTitle: '$(osName) .NET Core 3.1'
    condition: succeededOrFailed()

  - task: DotNetCoreCLI@2
    displayName: 'Run Unit Tests (.NET 5)'
    inputs:
      command: 'test'
      arguments: '--no-restore --no-build --framework net5.0 /noautorsp $(MSBuildArgs) "/BinaryLogger:$(ArtifactsDirectoryName)/test-net5.0.binlog"'
      testRunTitle: '$(osName) .NET 5.0'
    condition: succeededOrFailed()

  - task: DotNetCoreCLI@2
    displayName: 'Run Unit Tests (.NET 6)'
    inputs:
      command: 'test'
      arguments: '--no-restore --no-build --framework net6.0 /noautorsp $(MSBuildArgs) "/BinaryLogger:$(ArtifactsDirectoryName)/test-net6.0.binlog"'
      testRunTitle: '$(osName) .NET 6.0'
    condition: succeededOrFailed()

  - task: DotNetCoreCLI@2
    displayName: 'Run Unit Tests (.NET 7)'
    inputs:
      command: 'test'
      arguments: '--no-restore --no-build --framework net7.0 /noautorsp $(MSBuildArgs) "/BinaryLogger:$(ArtifactsDirectoryName)/test-net7.0.binlog"'
      testRunTitle: '$(osName) .NET 7.0'
    condition: succeededOrFailed()

  - task: DotNetCoreCLI@2
    displayName: 'Run Unit Tests (.NET 8)'
    inputs:
      command: 'test'
      arguments: '--no-restore --no-build --framework net8.0 /noautorsp $(MSBuildArgs) "/BinaryLogger:$(ArtifactsDirectoryName)/test-net8.0.binlog"'
      testRunTitle: '$(osName) .NET 8.0'
    condition: succeededOrFailed()

  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifacts'
    inputs:
      PathtoPublish: '$(ArtifactsDirectoryName)'
      ArtifactName: $(ArtifactsDirectoryName)-$(osName)
    condition: always()
