resources:
- repo: self

variables:
  ArtifactsDirectoryName: 'artifacts'
  BuildConfiguration: 'Debug'
  BuildPlatform: 'Any CPU'
  DotNetCore3Version: '3.x'
  DotNetCore5Version: '5.x'
  MSBuildArgs: '"/p:Platform=$(BuildPlatform)" "/p:Configuration=$(BuildConfiguration)" "/BinaryLogger:$(Build.SourcesDirectory)\$(ArtifactsDirectoryName)\msbuild.binlog"'
  SignType: 'Test'

trigger:
  batch: 'true'
  branches:
    include:
    - 'master'
    - 'rel/*'
  paths:
    exclude:
    - '*.md'
pr:
  branches:
    include:
    - master
    - 'rel/*'
  paths:
    exclude:
    - '*.md'

jobs:
- job: BuildAndTest
  displayName: 'Build and Test'
  pool:
    vmImage: windows-latest
  steps:
  - task: UseDotNet@2
    displayName: 'Install .NET Core $(DotNetCore3Version)'
    inputs:
      version: '$(DotNetCore3Version)'

  - task: UseDotNet@2
    displayName: 'Install .NET Core $(DotNetCore5Version)'
    inputs:
      version: '$(DotNetCore5Version)'
      includePreviewVersions: true

  - task: DotNetCoreCLI@2
    displayName: 'Build Solution'
    inputs:
      command: 'build'
      projects: 'SlnGen.sln'
      arguments: '$(MSBuildArgs)'

  - task: VSTest@2
    inputs:
      testSelector: 'testAssemblies'
      testAssemblyVer2: |
        **\*test*.dll
        !**\*TestAdapter.dll
        !**\obj\**
      searchFolder: '$(System.DefaultWorkingDirectory)'

  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifacts'
    inputs:
      PathtoPublish: '$(ArtifactsDirectoryName)'
      ArtifactName: $(ArtifactsDirectoryName)
    condition: always()