resources:
- repo: self

variables:
  ArtifactsDirectoryName: 'artifacts'
  BinaryLoggerArgs: '"/BinaryLogger:$(Build.SourcesDirectory)\$(ArtifactsDirectoryName)\msbuild.binlog"'
  BuildConfiguration: 'Debug'
  BuildPlatform: 'Any CPU'
  DotNetCoreVersion: '3.1.100'
  SignType: 'Test'

trigger:
  batch: true
  branches:
    include:
    - 'master'
    - 'rel/*'
  paths:
    exclude:
    - '*.md'
pr:
  branches:
    include:
    - master
    - 'rel/*'
  paths:
    exclude:
    - '*.md'

jobs:
- job: BuildAndTest
  displayName: 'Build and Test'
  pool:
    vmImage: windows-latest
  steps:
  - task: UseDotNet@2
    displayName: 'Install .NET Core $(DotNetCoreVersion)'
    inputs:
      version: '$(DotNetCoreVersion)'

  - task: MSBuild@1
    displayName: 'Build Solution'
    inputs:
      solution: SlnGen.sln
      platform: '$(BuildPlatform)'
      configuration: '$(BuildConfiguration)'
      msbuildArguments: '$(BinaryLoggerArgs)'

  - task: VSTest@2
    displayName: 'Run Unit Tests'
    inputs:
      testAssemblyVer2: |
       **\*Tests.dll
       !**\obj\**
      runInParallel: false

  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifacts'
    inputs:
      PathtoPublish: '$(ArtifactsDirectoryName)'
      ArtifactName: $(ArtifactsDirectoryName)
    condition: always()