resources:
- repo: self

variables:
  BuildConfiguration: 'Debug'
  BuildPlatform: 'Any CPU'
  DotNetCore3Version: '3.1.100'
  SignType: 'Test'

trigger:
  batch: true
  branches:
    include:
    - 'master'
  paths:
    exclude:
    - '*.md'
pr:
  branches:
    include:
    - master
  paths:
    exclude:
    - '*.md'

jobs:
- job: BuildAndTest
  displayName: 'Build and Test'
  pool:
    vmImage: windows-latest
  steps:
  - task: UseDotNet@2
    displayName: 'Install .NET Core 3.1'
    inputs:
      version: '$(DotNetCore3Version)'

  - task: MSBuild@1
    displayName: 'Build Solution'
    inputs:
      solution: SlnGen.sln
      platform: '$(BuildPlatform)'
      configuration: '$(BuildConfiguration)'
      msbuildArguments: '"/BinaryLogger:logs\msbuild.binlog"'

  - task: VSTest@2
    displayName: 'Run Unit Tests'
    inputs:
      testAssemblyVer2: |
       **\*Tests.dll
       !**\obj\**
      runInParallel: false

  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact: Logs'
    inputs:
      PathtoPublish: 'logs'
      ArtifactName: Logs
    condition: failed()